#!/usr/bin/env bash
# This script installs nginx on web-01 server
# Listening on port 80
# Returns string Hello World when queried at root

sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo /etc/init.d/nginx restart
sudo rm /var/www/html/*.html
sudo echo "Hello World" | sudo tee /var/www/html/index.html
