#!/usr/bin/env bash
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Hello World
# As an answer file, write a Bash script that configures a new Ubuntu machine to respect above requirements (this script will be run on the server itself)
# You can’t use systemctl for restarting nginx

find="^\tlocation / {"
replace="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"

sudo apt-get -y update
sudo apt-get install -y nginx
sudo rm /var/www/html/*.html
sudo echo "Hello World" | sudo tee /var/www/html/index.html
sudo sed -i "s|$find|$replace|" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
