#!/usr/bin/env bash
# Configures nginx on a new server so that its HTTP response contains a custom header
# where the name of the custom header is 'X-Served-By'
# and the value is the hostname of the Nginx is running on
FILE='server {\n\tlisten 80 default_server;\n\tlisten [::]:80 default_server;\n\troot /var/www/html;\n\tindex index.html index.htm index.nginx-debian.html;\n\tserver_name _;\n\tadd_header X-Served-By "\$hostname";\n\terror_page 404 /404.html;\n\tlocation /redirect_me {\n\t\treturn 301 https://youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\tlocation / {\n\t\ttry_files \$uri \$uri/ =404;\n\t}\n}'

sudo apt-get -y update
sudo apt-get install -y nginx
sudo rm /var/www/html/*.html
sudo echo "Hello World" | sudo tee /var/www/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo echo -e "$FILE" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
