#!usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

FRONTEND="frontend myfrontend\n\tbind :80\n\tdefault_backend myservers\n"
BACKEND="backend myservers\n\tbalance roundrobin\n\tserver 4917-web-01 54.173.52.0:80\n\tserver 4917-web-02 34.228.62.3\n"

sudo apt-get -y update
sudo apt-get -y install haproxy
echo -e "\n$FRONTEND\n$BACKEND\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo /etc/init.d/haproxy restart
